package collectors

import (
	"os"
	"path/filepath"
	"testing"
)

func TestParseDNSServers(t *testing.T) {
	// parseDNSServers reads from /etc/resolv.conf which won't exist on
	// Windows or may have unpredictable content in CI. Test the parsing
	// logic via a helper that reads from a temp file instead.

	tests := []struct {
		name     string
		content  string
		expected []string
	}{
		{
			name: "typical resolv.conf",
			content: `# Generated by NetworkManager
nameserver 192.168.1.1
nameserver 8.8.8.8
`,
			expected: []string{"192.168.1.1", "8.8.8.8"},
		},
		{
			name: "systemd-resolved stub",
			content: `# This is /run/systemd/resolve/stub-resolv.conf managed by systemd-resolved
nameserver 127.0.0.53
options edns0 trust-ad
search .
`,
			expected: []string{"127.0.0.53"},
		},
		{
			name: "duplicates deduplicated",
			content: `nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 8.8.8.8
`,
			expected: []string{"8.8.8.8", "8.8.4.4"},
		},
		{
			name:     "empty file",
			content:  "",
			expected: nil,
		},
		{
			name: "comments only",
			content: `# comment
# another comment
`,
			expected: nil,
		},
		{
			name: "with search and options",
			content: `search example.com
options timeout:2 attempts:3
nameserver 10.0.0.1
`,
			expected: []string{"10.0.0.1"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmp := filepath.Join(t.TempDir(), "resolv.conf")
			if err := os.WriteFile(tmp, []byte(tt.content), 0644); err != nil {
				t.Fatal(err)
			}

			got := parseDNSServersFrom(tmp)

			if len(got) != len(tt.expected) {
				t.Fatalf("got %v, want %v", got, tt.expected)
			}
			for i := range got {
				if got[i] != tt.expected[i] {
					t.Errorf("got[%d] = %q, want %q", i, got[i], tt.expected[i])
				}
			}
		})
	}
}
