package server

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"golang.org/x/crypto/bcrypt"
)

func TestLoadConfig_Defaults(t *testing.T) {
	cfg := LoadConfig()
	assert.Equal(t, 7331, cfg.Port)
	assert.Equal(t, "postgres://riot:riot@localhost:5432/riot?sslmode=disable", cfg.DBUrl)
	assert.Empty(t, cfg.RegistrationKey)
	assert.Equal(t, 30, cfg.RetentionDays)
	assert.NotEmpty(t, cfg.JWTSecret, "JWT secret should be auto-generated")
	assert.False(t, cfg.TLSEnabled)
	assert.Empty(t, cfg.AllowedOrigins)
}

func TestLoadConfig_PortOverride(t *testing.T) {
	t.Setenv("RIOT_PORT", "8080")
	cfg := LoadConfig()
	assert.Equal(t, 8080, cfg.Port)
}

func TestLoadConfig_InvalidPort(t *testing.T) {
	t.Setenv("RIOT_PORT", "notanumber")
	cfg := LoadConfig()
	assert.Equal(t, 7331, cfg.Port, "invalid port should keep default")
}

func TestLoadConfig_DBUrl(t *testing.T) {
	t.Setenv("RIOT_DB_URL", "postgres://other:other@db:5432/test")
	cfg := LoadConfig()
	assert.Equal(t, "postgres://other:other@db:5432/test", cfg.DBUrl)
}

func TestLoadConfig_RetentionDays(t *testing.T) {
	t.Setenv("RIOT_RETENTION_DAYS", "7")
	cfg := LoadConfig()
	assert.Equal(t, 7, cfg.RetentionDays)
}

func TestLoadConfig_APIKey(t *testing.T) {
	t.Setenv("RIOT_API_KEY", "my-secret-key")
	cfg := LoadConfig()
	assert.Equal(t, "my-secret-key", cfg.RegistrationKey)
}

func TestLoadConfig_JWTSecret(t *testing.T) {
	t.Setenv("RIOT_JWT_SECRET", "my-jwt-secret")
	cfg := LoadConfig()
	assert.Equal(t, "my-jwt-secret", cfg.JWTSecret)
}

func TestLoadConfig_JWTAutoGenerated(t *testing.T) {
	// No RIOT_JWT_SECRET set — should auto-gen a 64-char hex string
	cfg := LoadConfig()
	require.NotEmpty(t, cfg.JWTSecret)
	assert.Len(t, cfg.JWTSecret, 64, "auto-generated JWT secret should be 32 bytes hex-encoded")
}

func TestLoadConfig_AdminPassword(t *testing.T) {
	t.Setenv("RIOT_ADMIN_PASSWORD", "hunter2")
	cfg := LoadConfig()
	require.NotEmpty(t, cfg.AdminPasswordHash)
	err := bcrypt.CompareHashAndPassword([]byte(cfg.AdminPasswordHash), []byte("hunter2"))
	assert.NoError(t, err)
}

func TestLoadConfig_TLSEnabled(t *testing.T) {
	t.Setenv("RIOT_TLS_ENABLED", "true")
	cfg := LoadConfig()
	assert.True(t, cfg.TLSEnabled)
}

func TestLoadConfig_TLSDomainImpliesTLS(t *testing.T) {
	t.Setenv("RIOT_TLS_DOMAIN", "example.com")
	cfg := LoadConfig()
	assert.True(t, cfg.TLSEnabled)
	assert.Equal(t, "example.com", cfg.TLSDomain)
}

func TestLoadConfig_AllowedOrigins(t *testing.T) {
	t.Setenv("RIOT_ALLOWED_ORIGINS", "http://localhost:3000, https://example.com ,")
	cfg := LoadConfig()
	assert.Equal(t, []string{"http://localhost:3000", "https://example.com"}, cfg.AllowedOrigins)
}

func TestLoadConfig_GitHubRepo(t *testing.T) {
	t.Setenv("RIOT_GITHUB_REPO", "myorg/myrepo")
	cfg := LoadConfig()
	assert.Equal(t, "myorg/myrepo", cfg.GitHubRepo)
}

// [AC-030] Upgrade requires no configuration change: with none of the
// RIOT_OIDC_* or RIOT_TRUSTED_PROXIES variables set, every new field is
// empty and LoadConfig does not error.
func TestAC030_LoadConfig_NoOIDCVars_AllFieldsEmpty(t *testing.T) {
	cfg := LoadConfig()
	assert.Empty(t, cfg.OIDCIssuerURL)
	assert.Empty(t, cfg.OIDCClientID)
	assert.Empty(t, cfg.OIDCClientSecret)
	assert.Empty(t, cfg.OIDCButtonLabel)
	assert.Empty(t, cfg.TrustedProxies)
}

// [AC-003] Partial configuration: config.go reads each of the three required
// OIDC vars independently and verbatim (trimmed) — dormancy policy itself is
// applied by the oidc package, not here.
func TestAC003_LoadConfig_PartialOIDCConfig_FieldsPopulatedIndependently(t *testing.T) {
	t.Setenv("RIOT_OIDC_ISSUER_URL", "https://auth.example/application/o/riot/")
	t.Setenv("RIOT_OIDC_CLIENT_ID", "riot-client")
	// RIOT_OIDC_CLIENT_SECRET intentionally left unset.
	cfg := LoadConfig()
	assert.Equal(t, "https://auth.example/application/o/riot/", cfg.OIDCIssuerURL)
	assert.Equal(t, "riot-client", cfg.OIDCClientID)
	assert.Empty(t, cfg.OIDCClientSecret, "unset secret must remain empty, not defaulted")
}

func TestLoadConfig_OIDCVars_TrimmedWhitespace(t *testing.T) {
	t.Setenv("RIOT_OIDC_ISSUER_URL", "  https://auth.example/application/o/riot/  ")
	t.Setenv("RIOT_OIDC_CLIENT_ID", "  riot-client  ")
	t.Setenv("RIOT_OIDC_CLIENT_SECRET", "  s3cr3t  ")
	t.Setenv("RIOT_OIDC_BUTTON_LABEL", "  Sign in with authentik  ")
	cfg := LoadConfig()
	assert.Equal(t, "https://auth.example/application/o/riot/", cfg.OIDCIssuerURL)
	assert.Equal(t, "riot-client", cfg.OIDCClientID)
	assert.Equal(t, "s3cr3t", cfg.OIDCClientSecret)
	assert.Equal(t, "Sign in with authentik", cfg.OIDCButtonLabel)
}

func TestLoadConfig_OIDCVars_WhitespaceOnlyTrimsToEmpty(t *testing.T) {
	t.Setenv("RIOT_OIDC_CLIENT_SECRET", "   ")
	cfg := LoadConfig()
	assert.Empty(t, cfg.OIDCClientSecret)
}

func TestLoadConfig_TrustedProxies_AbsentIsEmpty(t *testing.T) {
	cfg := LoadConfig()
	assert.Empty(t, cfg.TrustedProxies)
}

func TestLoadConfig_TrustedProxies_ReadVerbatim(t *testing.T) {
	t.Setenv("RIOT_TRUSTED_PROXIES", "10.0.0.0/8, 192.168.1.1")
	cfg := LoadConfig()
	assert.Equal(t, "10.0.0.0/8, 192.168.1.1", cfg.TrustedProxies)
}
