package server

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"golang.org/x/crypto/bcrypt"
)

func TestLoadConfig_Defaults(t *testing.T) {
	cfg := LoadConfig()
	assert.Equal(t, 7331, cfg.Port)
	assert.Equal(t, "postgres://riot:riot@localhost:5432/riot?sslmode=disable", cfg.DBUrl)
	assert.Empty(t, cfg.RegistrationKey)
	assert.Equal(t, 30, cfg.RetentionDays)
	assert.NotEmpty(t, cfg.JWTSecret, "JWT secret should be auto-generated")
	assert.False(t, cfg.TLSEnabled)
	assert.Empty(t, cfg.AllowedOrigins)
}

func TestLoadConfig_PortOverride(t *testing.T) {
	t.Setenv("RIOT_PORT", "8080")
	cfg := LoadConfig()
	assert.Equal(t, 8080, cfg.Port)
}

func TestLoadConfig_InvalidPort(t *testing.T) {
	t.Setenv("RIOT_PORT", "notanumber")
	cfg := LoadConfig()
	assert.Equal(t, 7331, cfg.Port, "invalid port should keep default")
}

func TestLoadConfig_DBUrl(t *testing.T) {
	t.Setenv("RIOT_DB_URL", "postgres://other:other@db:5432/test")
	cfg := LoadConfig()
	assert.Equal(t, "postgres://other:other@db:5432/test", cfg.DBUrl)
}

func TestLoadConfig_RetentionDays(t *testing.T) {
	t.Setenv("RIOT_RETENTION_DAYS", "7")
	cfg := LoadConfig()
	assert.Equal(t, 7, cfg.RetentionDays)
}

func TestLoadConfig_APIKey(t *testing.T) {
	t.Setenv("RIOT_API_KEY", "my-secret-key")
	cfg := LoadConfig()
	assert.Equal(t, "my-secret-key", cfg.RegistrationKey)
}

func TestLoadConfig_JWTSecret(t *testing.T) {
	t.Setenv("RIOT_JWT_SECRET", "my-jwt-secret")
	cfg := LoadConfig()
	assert.Equal(t, "my-jwt-secret", cfg.JWTSecret)
}

func TestLoadConfig_JWTAutoGenerated(t *testing.T) {
	// No RIOT_JWT_SECRET set — should auto-gen a 64-char hex string
	cfg := LoadConfig()
	require.NotEmpty(t, cfg.JWTSecret)
	assert.Len(t, cfg.JWTSecret, 64, "auto-generated JWT secret should be 32 bytes hex-encoded")
}

func TestLoadConfig_AdminPassword(t *testing.T) {
	t.Setenv("RIOT_ADMIN_PASSWORD", "hunter2")
	cfg := LoadConfig()
	require.NotEmpty(t, cfg.AdminPasswordHash)
	err := bcrypt.CompareHashAndPassword([]byte(cfg.AdminPasswordHash), []byte("hunter2"))
	assert.NoError(t, err)
}

func TestLoadConfig_TLSEnabled(t *testing.T) {
	t.Setenv("RIOT_TLS_ENABLED", "true")
	cfg := LoadConfig()
	assert.True(t, cfg.TLSEnabled)
}

func TestLoadConfig_TLSDomainImpliesTLS(t *testing.T) {
	t.Setenv("RIOT_TLS_DOMAIN", "example.com")
	cfg := LoadConfig()
	assert.True(t, cfg.TLSEnabled)
	assert.Equal(t, "example.com", cfg.TLSDomain)
}

func TestLoadConfig_AllowedOrigins(t *testing.T) {
	t.Setenv("RIOT_ALLOWED_ORIGINS", "http://localhost:3000, https://example.com ,")
	cfg := LoadConfig()
	assert.Equal(t, []string{"http://localhost:3000", "https://example.com"}, cfg.AllowedOrigins)
}

func TestLoadConfig_GitHubRepo(t *testing.T) {
	t.Setenv("RIOT_GITHUB_REPO", "myorg/myrepo")
	cfg := LoadConfig()
	assert.Equal(t, "myorg/myrepo", cfg.GitHubRepo)
}
