package events

import "github.com/DesyncTheThird/rIOt/internal/models"

// AlertTemplates returns the hard-coded list of alert templates for quick creation.
func AlertTemplates() []models.AlertTemplate {
	return []models.AlertTemplate{
		// Service
		{
			ID:              "service_stopped",
			Name:            "Service Stopped",
			Category:        "service",
			Metric:          "service_state",
			Operator:        "==",
			Threshold:       1,
			TargetState:     "stopped",
			Severity:        "warning",
			CooldownSeconds: 900,
			NeedsTargetName: true,
			Description:     "Fires when a named service enters the stopped state",
		},
		{
			ID:              "service_failed",
			Name:            "Service Failed",
			Category:        "service",
			Metric:          "service_state",
			Operator:        "==",
			Threshold:       1,
			TargetState:     "failed",
			Severity:        "critical",
			CooldownSeconds: 300,
			NeedsTargetName: true,
			Description:     "Fires when a named service enters the failed state",
		},
		// Network
		{
			ID:              "nic_down",
			Name:            "NIC Down",
			Category:        "network",
			Metric:          "nic_state",
			Operator:        "==",
			Threshold:       1,
			TargetState:     "any",
			Severity:        "critical",
			CooldownSeconds: 300,
			NeedsTargetName: true,
			Description:     "Fires when a network interface is in any non-UP state",
		},
		// Process
		{
			ID:              "process_missing",
			Name:            "Process Not Running",
			Category:        "process",
			Metric:          "process_missing",
			Operator:        "==",
			Threshold:       1,
			TargetState:     "absent",
			Severity:        "warning",
			CooldownSeconds: 900,
			NeedsTargetName: true,
			Description:     "Fires when a named process is not found in the process list",
		},
		// System
		{
			ID:              "high_memory",
			Name:            "High Memory Usage",
			Category:        "system",
			Metric:          "mem_percent",
			Operator:        ">",
			Threshold:       90,
			Severity:        "warning",
			CooldownSeconds: 3600,
			NeedsTargetName: false,
			Description:     "Fires when memory usage exceeds the threshold",
		},
		{
			ID:              "high_disk",
			Name:            "High Disk Usage",
			Category:        "system",
			Metric:          "disk_percent",
			Operator:        ">",
			Threshold:       90,
			Severity:        "critical",
			CooldownSeconds: 3600,
			NeedsTargetName: false,
			Description:     "Fires when disk usage exceeds the threshold",
		},
		{
			ID:              "device_offline",
			Name:            "Device Offline",
			Category:        "system",
			Metric:          "device_offline",
			Operator:        "==",
			Threshold:       1,
			Severity:        "warning",
			CooldownSeconds: 300,
			NeedsTargetName: false,
			Description:     "Fires when a device stops sending heartbeats",
		},
		// Container
		{
			ID:              "container_died",
			Name:            "Container Died",
			Category:        "container",
			Metric:          "container_died",
			Operator:        "==",
			Threshold:       1,
			Severity:        "warning",
			CooldownSeconds: 900,
			NeedsTargetName: false,
			Description:     "Fires when a Docker container exits unexpectedly",
		},
		{
			ID:              "container_oom",
			Name:            "Container OOM Killed",
			Category:        "container",
			Metric:          "container_oom",
			Operator:        "==",
			Threshold:       1,
			Severity:        "critical",
			CooldownSeconds: 900,
			NeedsTargetName: false,
			Description:     "Fires when a Docker container is killed by the OOM killer",
		},
		// Container Thresholds
		{
			ID:              "container_high_cpu",
			Name:            "Container High CPU",
			Category:        "container",
			Metric:          "container_cpu_percent",
			Operator:        ">",
			Threshold:       80,
			Severity:        "warning",
			CooldownSeconds: 900,
			NeedsTargetName: true,
			Description:     "Fires when a container's CPU usage exceeds the threshold",
		},
		{
			ID:              "container_high_memory",
			Name:            "Container High Memory",
			Category:        "container",
			Metric:          "container_mem_percent",
			Operator:        ">",
			Threshold:       90,
			Severity:        "warning",
			CooldownSeconds: 900,
			NeedsTargetName: true,
			Description:     "Fires when a container's memory usage exceeds the threshold",
		},
		// UPS
		{
			ID:              "ups_on_battery",
			Name:            "UPS On Battery",
			Category:        "ups",
			Metric:          "ups_on_battery",
			Operator:        "==",
			Threshold:       1,
			Severity:        "warning",
			CooldownSeconds: 900,
			NeedsTargetName: false,
			Description:     "Fires when the UPS switches to battery power",
		},
		{
			ID:              "ups_low_battery",
			Name:            "UPS Low Battery",
			Category:        "ups",
			Metric:          "ups_battery_percent",
			Operator:        "<",
			Threshold:       20,
			Severity:        "critical",
			CooldownSeconds: 300,
			NeedsTargetName: false,
			Description:     "Fires when UPS battery charge drops below the threshold",
		},
		// Logs
		{
			ID:              "log_errors",
			Name:            "Log Errors Detected",
			Category:        "system",
			Metric:          "log_errors",
			Operator:        ">",
			Threshold:       0,
			Severity:        "warning",
			CooldownSeconds: 900,
			NeedsTargetName: false,
			Description:     "Fires when a device reports error-level or higher log entries",
		},
	}
}
